#!/bin/sh

# Check for root user
CURR_USER=`/usr/bin/whoami`
if [ "$CURR_USER" != "root" ]; then
	echo "I need root rights... Please login from root"
	exit
fi

echo "0" >  /proc/sys/net/ipv4/icmp_echo_ignore_all
